# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  database: moodycall_dev
  pool: 5
  timeout: 30000
  prepared_statement: false

staging:
  adapter: postgresql
  encoding: unicode
  database: staging
  pool: 5
  timeout: 8000
  prepared_statement: false

production:
  adapter: postgresql
  database: production
  pool: 5
  timeout: 8000
  prepared_statement: false